### ISSUE TITLE
Can be used to send fake emails

### ISSUE THREAD

**Issue by GeorgiosG** [wolf-pack/form#22]
Hello Nic,

Found a potential way to abuse the pluging.

What would be the preferred way to send you the details?

Regards,
GeorgiosG

**Comment by nicwortel** [comment]
Hey Georgios,

I am actually no longer actively maintaining the Form plugin, since I am no longer using Wolf CMS, but I can create a fix if this is a serious vulnerability. Just post the details here. If you think this should not be communicated over an open channel, let me know, then I will give you an email address you can send the details to.
